### ISSUE TITLE
Release 2.2.1

### ISSUE THREAD

**Issue by jwyderko** [CareEvolution/OrchestrateSDK#192]
This release is a minor fix to parameter handling on the `insight.risk_profile` function. This release issue should track the official testing prior to merge as well as discussion of the [release notes](https://github.com/CareEvolution/OrchestrateSDK/releases/edit/untagged-4dfa3628935071d6b393).

- [x] Full e2e tests are successful
- [x] The release notes fully cover all end-user features

**Comment by jeremytwfortune** [comment]
🚢 Looks good to me.

**Comment by jeremytwfortune** [comment]
Published.
